### ISSUE TITLE
Please post valid pics and docs regarding FPC routing

### ISSUE THREAD

**Issue by testack18** [3DO-EU/nozzle-camera#32]
Am I the only one having a hard time figuring out how to route the FPC within SB main body? 

What I want and checked:
I'm using the hartk 2 pieces PCB -> How to mount cam PCB?
Checking this issue which is already closed: [ #Stealthburner PCB Mount?](https://github.com/3DO-EU/nozzle-camera/issues/17)
On the recommended link there is no mount option. That link does not really a mount. Its just some fancy face for the SB and a bit of cutout for the USB cable. There is no proper mount option for the PCB inside the toolhead like the topic opener asked in issue #17 .
Also none of the STLs provided under [Cam_mount_SB mod by Panzarkatten](https://github.com/3DO-EU/nozzle-camera/tree/main/printers/Voron_Stealthburner/Cam_mount_SB%20mod%20by%20Panzarkatten) correlates to the [shown image](https://github.com/3DO-EU/nozzle-camera/blob/main/printers/Voron_Stealthburner/Cam_mount_SB%20mod%20by%20Panzarkatten/Images/Pcb_mount_in_SB.jpg).
Once you zoom in, the cam FPC cable is either just disappear somewhere in the body or is just folded back. It clearly just not moving downwards. Furthermore, none of the STL has that wide cutout shown in the image. You cannot see anything where that FPC goes as the picture taken on an angle where nothing can properly seen (marked with orange). Its impossible to track/learn how it supposed to be routed and the picture is... ehmm.. kinda questionable.
![Pcb_mount_in_SB](https://github.com/3DO-EU/nozzle-camera/assets/37906467/603f7c5a-0ba8-4549-85a7-9103ae91b0e4)

On the other hand, in the Voron_Stealtburner folder there is a picture referred as "[FPC_DONT_PULL.jpg](https://github.com/3DO-EU/nozzle-camera/blob/main/printers/Voron_Stealthburner/images/FPC_DONT_PULL.jpg)".
The marked with orange part is definietly much longer for the Magnum_plus_UHF than for the 'normal' cam_mount_SB. There is not enough room here to fold the ribbon cable as shown on that picture for the cam_mount_SB. If I would try to do it, it will definietly break the FPC.
![FPC_DONT_PULL](https://github.com/3DO-EU/nozzle-camera/assets/37906467/70ca09a1-28b4-4de0-87bf-3bf2bd63ba2d)

The [image](https://github.com/3DO-EU/nozzle-camera/blob/main/printers/Voron_Stealthburner/images/FPC_INTERNAL.jpg) shows how to route the FPC within the SB is not clear.
The cable channel goes up from the hotend fan to the top part cooling fan is not deep enough to push the FPC within. How is the cable folded there to avoid blocking the air coming from the part fan? From this angled picture its impossible to see.

In general, some of the pictures not correlates to the provided STLs and some of them are either bad or just not clear. 
Without clear documentation and pictures the risk to break that weak FPC is really high.
Please provide more pictures aligned with the uploaded STLs. 
Please provide pictures created from diferent angle to be able to track how it is designed, how it is supposed to be.

Or just say its not supported to mount the PCB within the SB toolhead. But in this case, do not put a 25cm FPC on the cam, if we have to mount on the ADXL mount point.

**Comment by panzarkatten** [comment]
Hi @testack18 and thanks for your feedback! I'll try to answer your questions below.

1. No there is no actual mount for the PCB inside the Stealthburner face since there just isn't that much room for a mount. I have tried to come up with good solution to no avail. Possibly without the 2-piece hartk board it would be doable but I have not explored that option. If you want to hold it in place maybe a small piece of VHB tape could work. For me the part cooling cable is enough to hold it in place. 

2. The wide cutout you see in the [image](https://user-images.githubusercontent.com/37906467/273040938-603f7c5a-0ba8-4549-85a7-9103ae91b0e4.jpg) is just because I broke off the small piece that is there in the model to make room for the LED dupont connector. 

3. It is possible to route the FPC as shown in the "do not pull" image on the non UHF version as well. But I would personally recommend to route the cable straight up and then do a 90 degree fold on the cable to avoid putting unnecessary strain on it where it attaches to the sensor.  
<p align="center">
<img src="https://github.com/3DO-EU/nozzle-camera/assets/64177768/91406c86-5b64-4902-8e8a-43723ff9d288" width="50%" /></p>

4. Here you have some extra images showing how I routed the FPC cable. It's routed along the right side and then above the hotend fan continuing up the cable path in the slit added to the model and then folded two times before reaching the PCB.  
<p align="center">
<img src="https://github.com/3DO-EU/nozzle-camera/assets/64177768/b9bee496-0ede-4bbb-88b1-86a51c3260fb" width=50% /><img src="https://github.com/3DO-EU/nozzle-camera/assets/64177768/b5d72f9d-885d-45a2-a512-83b5b63afc78" width="50%" />
<img src="https://github.com/3DO-EU/nozzle-camera/assets/64177768/9221515f-dbd9-4e11-afa2-095767b4abbf" width="50%" />
</p>

5. And for information, I have no affiliation with the company 3DO. I have just made and shared some SB face models with the camera mount etc.

**Comment by testack18** [comment]
Thanks for taking the time and answering detailed all my problems.
In the meanwhile I found [this ](https://www.printables.com/de/model/565312-3do-nozzle-camera-pcb-mount-cover-with-thermistor-)for PSB mount. Not exactly within the main body, but its hidden, not outside the SB. Maybe its useful for others as well.
